# 2022

- id: doi:10.1038/s41467-022-29988-w
  image: "images/papers/kidney.png"
  tags:
    - kidney
    - morphogenesis
    - tissues
    
# 2021   
    
- id: doi:10.1126/sciadv.abh3457
  image: "images/papers/the-fluid-shear-stress.jpeg"
  tags:
    - fluid shear stress
    - TRPM7
    - intravasation

# 2013

- id: doi:10.1016/j.biomaterials.2013.08.063
  image: "images/papers/biomaterials.png"
  tags:
    - cationic polymer
    - nanocomplex
    - gene delivery

- id: doi:10.1089/ten.teb.2012.0422
  image: "images/papers/tissue-engineering-b.png"
  tags:
    - hair follicle
    - multipotent stem cells
    - regenerative medicine

- id: doi:10.1007/978-1-62703-417-3_5
  image: "images/papers/emerging-trends.png"
  tags:
    - hair follicle
    - stem cells
    - gene therapy

# 2012

- id: doi:10.1002/stem.1223
  image: "images/papers/nanog-reverses.png"
  tags:
    - Nanog
    - Organismal Aging
    - mesenchymal stem cells

- id: doi:10.1093/cvr/cvs253
  image: "images/papers/functional-vascular.png"
  tags:
    - smooth muscle cells
    - human induced pluripotent stem cells

- id: doi:10.1016/j.scr.2011.07.003
  image: "images/papers/clonal-multipotency.png"
  tags:
    - clonal multipotency
    - human hair follicle
    - mesenchymal stem cells

# 2008

- id: doi:10.1016/j.jbiotec.2008.07.600
  image: "images/papers/biotransformations.png"
  tags:
    - biotransformations
    - natural compounds
    - derivatives

# 2007

- id: doi:10.1016/j.jtemb.2007.09.004
  image: "images/papers/trace-elements.png"
  tags:
    - human cerebrospinal fluid
    - capillary electrophoresis
    - manganese species

- id: doi:10.1002/elps.200600686
  image: "images/papers/electrophoresis.png"
  tags:
    - human cerebrospinal fluid
    - coupled plasma
    - manganese species

- id: doi:10.1039/B610639K
  image: "images/papers/manganese.jpeg"
  tags:
    - cerebrospinal fluid
    - plasma mass spectrometry
    - manganese species
  
    
